url: https://hicai-zju.github.io
baseurl: 

# Site settings
title:
email: huajunsir@zju.edu.cn
description: "An AI for science team from Hangzhou Innovation Center of Zhejiang University."


# Team names, titles and social links
people-pi:
- name: Prof. Qiang Zhang
  pic: PI/1
  position: PI Researcher
  url: #

- name: Prof. Keyan Ding
  pic: PI/2
  position: PI Researcher
  url: #

- name: Prof. Renjun Xu
  pic: PI/3
  position: PI Researcher
  url: #

people-student:
- name: Zeyuan Wang
  pic: student/1
  position: PhD Student
  url: #

- name: Min Qin
  pic: student/2
  position: PhD Student
  url: #

- name: Diana Petersen
  pic: student/3
  position: Lead Developer
  url: #

- name: Diana Petersen
  pic: student/3
  position: Lead Developer
  url: #

people-ra:
    - name: Huajun Chen
      pic: ra/1
      position: Professor
      url: #

    - name: Larry Parker
      pic: ra/2
      position: Lead Marketer
      url: #

    - name: Diana Petersen
      pic: ra/3
      position: Lead Developer
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Homepage
    url: http://zjukg.org
  - title: twitter
    url:
  - title: github
    url: http://github.com/hicai-zju

# Postal address (add as many lines as necessary)
#address:
 # - line: 3481 Melrose Place
  #- line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty