url: https://hicai-zju.github.io
baseurl: 

# Site settings
title: AGI for Science
email: huajunsir@zju.edu.cn
description: "An AGI for science team from Hangzhou Innovation Center of Zhejiang University."


# Team names, titles and social links
people:
- name: Huajun Chen
  pic: 1
  position: Professor
  social:
    - title: homepage
      url: https://person.zju.edu.cn/en/huajun

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
- name: Huajun Chen
  pic: 1
  position: Professor
  social:
    - title: homepage
      url: https://person.zju.edu.cn/en/huajun

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: Homepage
    url: http://zjukg.org
  - title: twitter
    url:
  - title: github
    url: http://github.com/hicai-zju

# Postal address (add as many lines as necessary)
#address:
 # - line: 3481 Melrose Place
  #- line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty